import type { ObjectClass, Physics } from "./schema";

type Spec = Omit<Physics, "movable"> & { movable?: boolean };

const TABLE: Record<ObjectClass, Spec> = {
  pallet_rack: {
    body: "static",
    mass_kg: null,
    material: "painted_steel",
    friction: 0.55,
    restitution: 0.05,
    support_surface: true,
    traversable: false,
  },
  pallet: {
    body: "dynamic",
    mass_kg: 28,
    material: "hardwood",
    friction: 0.45,
    restitution: 0.12,
    support_surface: true,
    traversable: false,
    movable: true,
  },
  carton: {
    body: "dynamic",
    mass_kg: 8.5,
    material: "corrugated_cardboard",
    friction: 0.4,
    restitution: 0.08,
    support_surface: true,
    traversable: false,
    movable: true,
  },
  bin: {
    body: "dynamic",
    mass_kg: 4.2,
    material: "hdpe",
    friction: 0.35,
    restitution: 0.15,
    support_surface: true,
    traversable: false,
    movable: true,
  },
  forklift: {
    body: "kinematic",
    mass_kg: 4200,
    material: "painted_steel",
    friction: 0.7,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
    movable: true,
  },
  pallet_jack: {
    body: "dynamic",
    mass_kg: 90,
    material: "steel",
    friction: 0.5,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
    movable: true,
  },
  conveyor: {
    body: "static",
    mass_kg: null,
    material: "steel_belt",
    friction: 0.25,
    restitution: 0.02,
    support_surface: true,
    traversable: false,
  },
  dock_door: {
    body: "kinematic",
    mass_kg: 180,
    material: "insulated_steel",
    friction: 0.4,
    restitution: 0.1,
    support_surface: false,
    traversable: true,
  },
  column: {
    body: "static",
    mass_kg: null,
    material: "reinforced_concrete",
    friction: 0.7,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
  },
  wall: {
    body: "static",
    mass_kg: null,
    material: "cmu_or_drywall",
    friction: 0.6,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
  },
  door: {
    body: "kinematic",
    mass_kg: 45,
    material: "hollow_metal",
    friction: 0.4,
    restitution: 0.1,
    support_surface: false,
    traversable: true,
  },
  shelf: {
    body: "static",
    mass_kg: null,
    material: "powder_coated_steel",
    friction: 0.5,
    restitution: 0.05,
    support_surface: true,
    traversable: false,
  },
  display: {
    body: "static",
    mass_kg: 55,
    material: "mdf_laminate",
    friction: 0.45,
    restitution: 0.08,
    support_surface: true,
    traversable: false,
  },
  counter: {
    body: "static",
    mass_kg: null,
    material: "laminate_over_ply",
    friction: 0.4,
    restitution: 0.05,
    support_surface: true,
    traversable: false,
  },
  fixture: {
    body: "static",
    mass_kg: 30,
    material: "mixed_retail",
    friction: 0.45,
    restitution: 0.08,
    support_surface: true,
    traversable: false,
  },
  cart: {
    body: "dynamic",
    mass_kg: 18,
    material: "steel_wire",
    friction: 0.2,
    restitution: 0.1,
    support_surface: true,
    traversable: false,
    movable: true,
  },
  vehicle: {
    body: "kinematic",
    mass_kg: 1800,
    material: "automotive",
    friction: 0.75,
    restitution: 0.1,
    support_surface: false,
    traversable: false,
    movable: true,
  },
  person: {
    body: "kinematic",
    mass_kg: 75,
    material: "body",
    friction: 0.6,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
    movable: true,
  },
  safety_barrier: {
    body: "static",
    mass_kg: 12,
    material: "polymer",
    friction: 0.4,
    restitution: 0.25,
    support_surface: false,
    traversable: false,
  },
  signage: {
    body: "static",
    mass_kg: 3,
    material: "aluminum_composite",
    friction: 0.35,
    restitution: 0.1,
    support_surface: false,
    traversable: false,
  },
  lighting: {
    body: "static",
    mass_kg: 6,
    material: "aluminum",
    friction: 0.3,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
  },
  hvac: {
    body: "static",
    mass_kg: null,
    material: "galvanized_steel",
    friction: 0.4,
    restitution: 0.05,
    support_surface: false,
    traversable: false,
  },
  floor_marking: {
    body: "static",
    mass_kg: 0,
    material: "epoxy_paint",
    friction: 0.55,
    restitution: 0.01,
    support_surface: true,
    traversable: true,
  },
  debris: {
    body: "dynamic",
    mass_kg: 6,
    material: "mixed_construction",
    friction: 0.55,
    restitution: 0.15,
    support_surface: false,
    traversable: false,
    movable: true,
  },
  unknown: {
    body: "static",
    mass_kg: null,
    material: "unknown",
    friction: 0.5,
    restitution: 0.1,
    support_surface: false,
    traversable: false,
  },
};

export function physicsFor(cls: ObjectClass, massScale = 1): Physics {
  const spec = TABLE[cls];
  const movable = spec.movable ?? spec.body !== "static";
  return {
    body: spec.body,
    mass_kg:
      spec.mass_kg === null ? null : Math.round(spec.mass_kg * massScale * 10) / 10,
    material: spec.material,
    friction: spec.friction,
    restitution: spec.restitution,
    support_surface: spec.support_surface,
    traversable: spec.traversable,
    movable,
  };
}

export const AFFORDANCES: Record<ObjectClass, string[]> = {
  pallet_rack: ["storage", "obstacle", "climb_hazard"],
  pallet: ["grasp", "fork", "stack", "push"],
  carton: ["grasp", "stack", "push"],
  bin: ["grasp", "contain", "push"],
  forklift: ["drive", "avoid"],
  pallet_jack: ["push", "pull"],
  conveyor: ["transport", "pinch_hazard"],
  dock_door: ["open", "threshold"],
  column: ["obstacle"],
  wall: ["obstacle", "boundary"],
  door: ["open", "threshold"],
  shelf: ["storage", "pick"],
  display: ["obstacle", "browse"],
  counter: ["work_surface", "obstacle"],
  fixture: ["obstacle"],
  cart: ["push", "contain"],
  vehicle: ["drive", "avoid"],
  person: ["avoid", "yield"],
  safety_barrier: ["obstacle", "guide"],
  signage: ["read"],
  lighting: ["ignore"],
  hvac: ["ignore"],
  floor_marking: ["follow", "lane"],
  debris: ["avoid", "clear"],
  unknown: ["inspect"],
};
